title: Github pages with Jekyll
author: Yannier Gonzalez
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my description.

# theme
theme: minima

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
